################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package test jacoco:report

#####################
### After Success ###
#####################
after_success:
  - bash <(curl -s https://codecov.io/bash)
